Repository atlp-rwanda/ecommerce-app-cogito-fe, pull requests merged in 2023-06, with the labels that each got.

#1 #FN:16 chore: Setting up an empty react project
  .editorconfig
  .eslintrc.cjs
  .gitattributes
  .github/Pull-Request-Template.md
  .gitignore
  .yarnrc.yml
  index.html
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/favicon.ico
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  tslint.json
  vite.config.ts
  yarn.lock
Labels: ready to be merged

#3 #FN-52 chore :Setup styling
  package.json
  postcss.config.js
  src/App.tsx
  src/index.css
  src/styles.scss
  tailwind.config.js
  yarn.lock
Labels: need review, Ready for TTL Review

#7 #FN-51 chore: Configure storybook for component development
  .babelrc
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/components/Button.tsx
  src/stories/Button.stories.ts
  yarn.lock
Labels: need review, Ready for TTL Review

#5 #FN:15 chore: Setting up Redux Tool Kit
  .gitignore
  package.json
  src/App.tsx
  src/assets/loading.svg
  src/components/index.tsx
  src/main.tsx
  src/redux/action/IndexAction.tsx
  src/redux/reducers/IndexSlice.tsx
  src/redux/store/index.tsx
  src/utils/api.tsx
  vite.config.ts
  yarn.lock
Labels: need review, Ready for TTL Review

#10 #FN-50: Configure TSLint and Git Pre commit hook
  .babelrc
  .eslintrc.cjs
  .github/Pull-Request-Template.md
  .prettierrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  package.json
  postcss.config.js
  src/App.tsx
  src/components/Button.tsx
  src/components/header.tsx
  src/components/index.tsx
  src/index.css
  src/main.tsx
  src/pages/home.tsx
  src/redux/action/IndexAction.tsx
  src/redux/index.tsx
  src/redux/reducers/IndexSlice.tsx
  src/redux/store/index.tsx
  src/routes/route.tsx
  src/services/index.tsx
  src/states/state.tsx
  src/stories/chat.tsx
  src/styles.scss
  src/styles/style.tsx
  src/utils/api.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: Ready for TTL Review

#6 #FN:55 chore: Setting Up Test
  .babelrc
  jest.config.ts
  package.json
  src/App.tsx
  src/components/Greet.tsx
  src/test/Greet.test.tsx
  yarn.lock
Labels: Ready for TTL Review

#4 #FN-53 chore: Setup CI/CD pipeline
  .circleci/config.yml
  .github/workflows/ci.yml
  .gitignore
  README.md
  package.json
Labels: Ready for TTL Review

#8 #FN:56 chore: Setting up Router
  package.json
  src/App.tsx
  src/components/HomePage.tsx
  src/components/Login.tsx
  src/styles.scss
  src/views/Home.tsx
  src/views/Login.tsx
  yarn.lock
Labels: Ready for TTL Review

#12 fix(actions): Fix github actions
  .github/workflows/ci.yml
  package.json
Labels: Ready for TTL Review

#21 #FN-144 chore: create top navigation bar and footer
  .babelrc
  .storybook/main.ts
  .storybook/preview.ts
  babel-plugin-macros.config.js
  desktop.ini
  jest.config.ts
  package.json
  src/App.tsx
  src/assets/desktop.ini
  src/assets/images/Logo.png
  src/assets/images/desktop.ini
  src/assets/images/payment1.png
  src/assets/images/payment11.png
  src/assets/images/payment2.jpg
  src/assets/images/payment22.jpg
  src/assets/images/payment3.jpg
  src/assets/images/payment32.jpg
  src/assets/images/payment33.png
  src/assets/images/payment4.jpg
  src/assets/images/payment44.jpg
  src/assets/images/payment5.png
  src/assets/images/payment6.png
  src/assets/images/payment62.png
  src/components/Button.tsx
  src/components/Footer/footer.test.tsx
  src/components/Footer/footer.tsx
  src/components/Greet.tsx
  src/components/Nav/nav.test.tsx
  src/components/Nav/navBar.tsx
  src/components/categories.tsx
  src/components/index.tsx
  src/desktop.ini
  src/pages/home.tsx
  src/redux/hooks/hooks.tsx
  src/redux/index.tsx
  src/redux/store/index.tsx
  src/stories/Button.stories.ts
  src/test/Greet.test.tsx
  src/utils/token.tsx
  src/views/Home.tsx
  tailwind.config.js
  test/__mocks__/fileMock.tsx
  vite.config.ts
  yarn.lock
Labels: need review, Ready for TTL Review

#18 #FN-17 feat: reset password
  .yarnrc.yml
  package-lock.json
  package.json
  src/App.tsx
  src/components/Nav/navBar.tsx
  src/pages/resetPassword/resetPassword.test.tsx
  src/pages/resetPassword/resetPassword.tsx
  src/pages/resetPassword/updatePassword.test.tsx
  src/pages/resetPassword/updatePassword.tsx
  src/redux/action/resetPasswordAction.tsx
  src/redux/reducers/resetPassword/resetPasswordSlice.tsx
  src/redux/reducers/resetPassword/updatePassword.tsx
  src/redux/store/index.tsx
  src/redux/store/loginStore.tsx
  src/redux/store/store.tsx
  yarn.lock
Labels: Ready for TTL Review

#17 #FN-49 Feat: User should sign up
  package.json
  src/---tests---/signup.test.tsx
  src/App.tsx
  src/components/Button.tsx
  src/components/index.tsx
  src/components/register.tsx
  src/components/socialIcon.tsx
  src/main.tsx
  src/pages/confirmationPage.tsx
  src/pages/register.tsx
  src/redux/action/registerAction.tsx
  src/redux/hooks/hooks.tsx
  src/redux/reducers/IndexSlice.tsx
  src/redux/reducers/userSlice.tsx
  src/redux/store/index.tsx
  src/redux/store/loginStore.tsx
  src/redux/store/store.tsx
  src/views/Home.tsx
  src/views/confirmation.tsx
  vercel.json
  yarn.lock
Labels: Ready for TTL Review

#19 #FN-48 feat: Two factor authentication
  .babelrc
  src/App.tsx
  src/assets/authIcons/lock.png
  src/assets/authIcons/lock.svg
  src/assets/authIcons/lockDanger.png
  src/assets/authIcons/lockDanger.svg
  src/components/Footer/footer.tsx
  src/components/Login.tsx
  src/components/Nav/nav.test.tsx
  src/components/TwoFactorAuth.tsx
  src/pages/TwoFactorAuth.tsx
  src/redux/action/GetOtp.tsx
  src/redux/action/TfaAction.tsx
  src/redux/action/loginAction.tsx
  src/redux/reducers/GetOtpSlice.tsx
  src/redux/reducers/TfaSlice.tsx
  src/redux/store/store.tsx
  src/test/Tfa.test.tsx
  vite.config.ts
Labels: Ready for TTL Review
